services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./front:/app
      - front_node_modules:/app/node_modules
    command: yarn dev -p 4000
    ports:
      - "4000:4000"
    networks:
      fixed_compose_network:
        ipv4_address: 172.27.0.2
  back:
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    environment:
      RAILS_ENV: development
      TZ: Asia/Tokyo
      REDIS_URL: "redis://redis:6379"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ./back:/app
    depends_on:
      - redis
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    networks:
      fixed_compose_network:
        ipv4_address: 172.27.0.3
  worker:
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    environment:
      RAILS_ENV: development
      TZ: Asia/Tokyo
    command: bash -c "bundle exec rake solid_queue:start"
    volumes:
      - ./back:/app
    networks:
      fixed_compose_network:
        ipv4_address: 172.27.0.4
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    networks:
      fixed_compose_network:
        ipv4_address: 172.27.0.5
networks:
  fixed_compose_network:
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/24
volumes:
  front_node_modules:
