services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    user: "root"
    environment:
      RAILS_ENV: development
      BUNDLE_WITHOUT: "null"
      BUNDLE_DEPLOYMENT: ""
      BUNDLE_PATH: "/app/.bundle"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ./back:/app
      - /etc/ssl/cert.pem:/etc/ssl/cert.pem
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front:/app
    command: yarn dev -p 4000
    ports:
      - "8000:4000"