development:
  adapter: redis
  url: redis://redis:6379/1

test:
  adapter: test

production:
  adapter: redis
  url: <%= Rails.application.credentials.dig(:redis, :url) %>
  channel_prefix: app_production
