inherit_from: .rubocop_todo.yml

# inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot

# 人の手で変更しないことが前提のファイルは除外
AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - db/**/*
    - vendor/**/*

# ********************
# RailsのCops詳細設定
# ********************
# ドキュメントの無い public class を許可する
Style/Documentation:
  Enabled: false

# 日本語コメントを許可する
Style/AsciiComments:
  Enabled: false

# DBディレクトリのファイルはABCサイズをチェックしない
Metrics/AbcSize:
  Max: 30
  Exclude:
    - "db/**/*"

# DBディレクトリのファイルはメソッドの長さをチェックしない
Metrics/MethodLength:
  Max: 20
  Exclude:
    - "db/**/*"

# 行の長さを100文字までに制限
Layout/LineLength:
  Max: 100
  Exclude:
    - "db/migrate/*"
    - "Gemfile"
    - "config/**/*"

#　文末のカンマを許可
Style/TrailingCommaInArguments:
  Exclude:
    - "db/fixtures/*"

# ファイルの先頭に文字列をfreezeするかの記述を強制するチェックを無効化
Style/FrozenStringLiteralComment:
  Enabled: false

# ブロック行数の制限を無効化
Metrics/BlockLength:
  Exclude:
    - "db/migrate/*"
    - "db/schema.rb"
    - "db/seeds.rb"
    - "spec/**/*"
    - "config/**/*"

# itブロック内で複数のexpectを許可
RSpec/MultipleExpectations:
  Enabled: false

# テストのネストを4階層までに制限
RSpec/NestedGroups:
  Max: 4

# テスト内のコード行数を8行までに制限（デフォルト5）
RSpec/ExampleLength:
  Max: 8
