name: Fly Deploy
on:
  push:
    branches:
      - main
    paths:
      - 'back/**'
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy back/ --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}